### ISSUE TITLE
Adding Nilan Gateway on another subnet

### ISSUE THREAD

**Issue by DKAutomater** [superrob/genvexconnect#5]
Hi Robin

I will like to see the config flow dont search on the home assistant subnet for nilan gateway only.

It could be nice to have the genvex connect to manually enter ip address for the gateway.

nice work

**Comment by superrob** [comment]
The search is performed by broadcasting an UDP packet, for which the gateway listens and responds to.
That breaks when the devices don't share the same subnet (This would most likely also be an issue in the official Nilan/Genvex apps?).

Manual IP entry isn't implemented currently. I originally had that planned, but choose to use the discovery approach as it allows for finding the device even if the IP changed for some reason, leading to a better experience for the most common home network setup.

**Comment by superrob** [comment]
There are currently no option of adding it in manually. The integration saves your device ID and upon startup runs the discovery process to get the current IP.
I agree on static IP's being the best option, however most consumers just run their ISP provided routers with DHCP.

Running multiple vlans is a much more advanced usecase :)

In order to support manual IP entry, both the integration and the libary would need changes.

**Comment by superrob** [comment]
Newest version allows for manual IP and port entry now.

**Comment by DKAutomater** [comment]
Great work
Thanks alot

Mvh Thomas Nielsen
________________________________
Fra: Robin Madsen ***@***.***>
Sendt: Tuesday, August 13, 2024 5:32:44 PM
Til: superrob/genvexconnect ***@***.***>
Cc: DKAutomater ***@***.***>; Author ***@***.***>
Emne: Re: [superrob/genvexconnect] Adding Nilan Gateway on another subnet (Issue #5)


Newest version allows for manual IP and port entry now.
